#!/bin/bash

##########################
#SBATCH --time 48:00:00 #specify a time limit for the job.
#SBATCH --job-name=AM_OF
#SBATCH --output am_of-%j.out
#SBATCH --partition=48hour
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=28
#SBATCH --exclusive
#SBATCH --mail-user=adam2.marshall@northumbria.ac.uk
#SBATCH --mail-type=ALL
##########################

nodes=$SLURM_JOB_NUM_NODES            # Number of nodes
cores=28                              # number of cores

sed -i "/numberOfSubdomains/c\\numberOfSubdomains    $(($nodes*$cores));" system/decomposeParDict

# Run the solution (parallel)
echo "SOLVING..."
decomposePar -force
mpirun -np $(($nodes*$cores)) renumberMesh -parallel -overwrite
mpirun -np $(($nodes*$cores)) potentialFoam -initialiseUBCs -noFunctionObjects -parallel
mpirun -np $(($nodes*$cores)) simpleFoam -parallel

reconstructPar -latestTime